### ISSUE TITLE
MySQL error when I try to delete content

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#1]
I get the error below when I try to delete a piece of content. If I click "close", I can then confirm the deletion and it seems to delete the page.

Steps to replicate:
- Select a piece of content
- Choose "delete" from the Actions menu

![image](https://cloud.githubusercontent.com/assets/4900157/9436771/0e5b49d6-4a95-11e5-8610-895dc26dc6e8.png)

**Comment by bradcbennett** [comment]
Similarly, the error below is thrown when I change the content type.

To replicate:
- Select a piece of content in the CMS
- Select "change document type" in the Actions menu
- Set New Type to ContentPage and click "Save"

If I then refresh the screen, the error seems to go away.

![image](https://cloud.githubusercontent.com/assets/4900157/9436871/cef62ca6-4a95-11e5-8528-3f09bece9230.png)

**Comment by atulnarang** [comment]
I believe this has been resolved because there was another similar issue raised which has been closed.

**Comment by bradcbennett** [comment]
Yep, all good.
Thanks.
