### ISSUE TITLE
Define h3 tag

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#10]
Currently h3 appears as regular text. See my test at the bottom of this page: http://prime.anony.im/about-us/who-we-are/ 

Please define h3 as Avenir Black slightly larger than regular text.

**Comment by atulnarang** [comment]
We followed the photoshop design, it would be great if you can share the guidelines for diff elements.

**Comment by bradcbennett** [comment]
As these are template designs, some minor elements will come as we implement the designs. H3, for example, is missing from your coded template.
So, please use something like AvenirHeavy 16px

![image](https://cloud.githubusercontent.com/assets/4900157/9728559/19c7f374-564c-11e5-8d41-67683b319c4d.png)

**Comment by atulnarang** [comment]
This was done and have used AvenirBlack

**Comment by bradcbennett** [comment]
Hi Atul,

Sorry for the confusion on my side, but I asked Nelson to lay out the styles just in case. Please see the bottom of this PSD (under the 'Fetch your super' heading):
https://www.dropbox.com/s/0bpnxzzx8cnyk7c/PrimeSuper_%20Forms%20Publications.psd?dl=0 
This includes:
1) H3 at 18px (slightly smaller than h2)
2) "List" at 12px. Note: "list" is what it is called in the WYSWYG editor as is different from the bullet points. "List" is to be used for the fine print across the site and so should be slightly smaller than normal paragraph text.

Thanks.

**Comment by atulnarang** [comment]
can you give example of on what page list is used? when i tried from the HTML Editor list is not selectable..

**Comment by bradcbennett** [comment]
hmmm ... that's odd. 
Can we make it selectable in the HTML editor? Or can we define a new style for the fine print?

**Comment by atulnarang** [comment]
Unfortunately it's a functional issue so we need to debug the code which is not possible as of now. We can reduce the font size of the fine print in the bottom which is "Important notice" to 11px. Please confirm.

**Comment by bradcbennett** [comment]
Will follow up with the client on text to manually make smaller.

**Comment by bradcbennett** [comment]
Hi Atul,

Here are the bits of text that need to be reduced in size


http://prime.anony.im/personal/great-insurance-rates/your-insurance-options/
*Premiums are payable directly by you, and not taken out of your super account.
 
http://prime.anony.im/employers-self-employed/key-benefits-of-joining-prime-super/
The Prime Super clearing house service is provided by SCH Online. SCH Online is operated by The Superannuation Clearing House Pty Limited (ABN15 086 576 721, AR 290290) issued by Pacific Custodians Pty Limited (ABN 66 009 682 866, AFSL 295142).
 
http://prime.anony.im/employers-self-employed/clearing-house/
*Contact the ATO for further information.

**SCH-Online is operated by The Superannuation Clearing House Pty Limited (ABN15 086 576 721, AR 290290) issued by Pacific Custodians Pty Limited (ABN 66 009 682 866, AFSL 295142). Separate fees, terms and conditions apply. Please refer to the Superannuation Clearing House Pty Limited’s Financial Services Guide and Refer to the SCH Online PDS available from www.sch-online.com.au for more details.

http://prime.anony.im/products/advice/
* Limited advice is provided through Money Solutions Pty Ltd (AFSL 258145).

# Prime Super Financial Planners are authorised representatives of PGW Financial Services Pty Ltd (PGW) AFSL384713, ABN 15 123 835 441.

http://prime.anony.im/tools-resources/learning-centre/tax-benefits-of-super/
* All rates quoted are current as at September 2015. For further information and the most up to date rates refer to the ato.com.au

**Comment by atulnarang** [comment]
added a new class "finePrint" to above elements

**Comment by bradcbennett** [comment]
Looks good.
Thanks.
