### ISSUE TITLE
Desktop Homepage: many alignment issues

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#13]
- space on the right of the drop down menu
- Sub-head spacing above the image tiles in the middle of the page
- Length of hairline above video
- Right margin on Login and Search
- Space around vertical hairline between 2nd and 3rd columns
- Vertical space around main nav text

Tested Chrome on Mac.

![image](https://cloud.githubusercontent.com/assets/4900157/9724162/47f622d8-5616-11e5-8c2f-eaf9da1aae31.png)

**Comment by atulnarang** [comment]
we are looking into it
