### ISSUE TITLE
"Select a state" drop down

### ISSUE THREAD

**Issue by atulnarang** [bradcbennett/PrimeSuper.com.au#16]
Is it needed Brad as per the previous PSDs or needs to be removed according to the latest PSDs?

**Comment by bradcbennett** [comment]
Hi Atul,

Yes, please keep the "select a state" drop down. Clicking on an option should take the user to an anchor link on the Contact a Regional Manager page.

**Comment by bradcbennett** [comment]
looks like not all of the items in the drop down work. Tested with Chrome on Windows.
The following links don't work from the state drop down:
http://prime.anony.im/contact-us/contact-a-regional-manager#nt
http://prime.anony.im/contact-us/contact-a-regional-manager#qld
http://prime.anony.im/contact-us/contact-a-regional-manager (which should be an anchor link for ACT)
http://prime.anony.im/contact-us/contact-a-regional-manager#vic (links to TAS)

**Comment by atulnarang** [comment]
These work same as on live site here : http://primesuper.com.au

**Comment by bradcbennett** [comment]
Ok.
Lets make them work properly then. 
Thanks.

**Comment by atulnarang** [comment]
works now

**Comment by bradcbennett** [comment]
The anchor linking works great. Thanks.

Now, can we tweak the roll-over state to be the entire cell? Screenshot from Chrome / Mac below.

![image](https://cloud.githubusercontent.com/assets/4900157/10034155/ae93d71c-61d1-11e5-80ba-03590be809c0.png)

**Comment by atulnarang** [comment]
fixed
