### ISSUE TITLE
Paragraph text on Landing page is inconsistent

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#17]
The first paragraph below the About Us header is styled differently from the second paragraph. Also, the space between the paragraphs is too large.

"Prime Super is an independent profit-to-members ..." is different from
"We take the complexity out ..."

![image](https://cloud.githubusercontent.com/assets/4900157/9836189/52146676-5a53-11e5-87c8-e8900efad3a5.png)

**Comment by atulnarang** [comment]
This has been fixed and font size is as per the Personal page.
