### ISSUE TITLE
Remove h4 - h6 from WYSIWYG

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#18]
These undefined styles are causing some confusion with the client.

**Comment by atulnarang** [comment]
Are you talking about the "wysiwyg" div? If yes, the content needs to be edited from the CMS to remove these tags. Please let me know if you are referring to the actual editor.

**Comment by bradcbennett** [comment]
I'm referring to the actual editor. Probably easier to remove h4-h6 from the editor rather than define these styles.

![image](https://cloud.githubusercontent.com/assets/4900157/9863463/7fa7b63e-5b83-11e5-9fa4-ff78f038cd02.png)

**Comment by atulnarang** [comment]
The whole style can be removed Brad and only h4-h6, please advise

**Comment by bradcbennett** [comment]
OK. 
As discussed, please add styles for h4-h6 to the css.

**Comment by atulnarang** [comment]
Can you please provide the font size for h4, h5 and h6?

**Comment by bradcbennett** [comment]
Let's go with 
H4=16
H5=15
H6=14

Thanks.

**Comment by atulnarang** [comment]
Done
