### ISSUE TITLE
Update <li> styles

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#19]
Please use the dark text with blue dot rather than the orange.
See the attached design

![primesuper_-getting-started](https://cloud.githubusercontent.com/assets/4900157/9836235/9ae452ac-5a54-11e5-90b3-36b08508e2f5.jpg)

**Comment by atulnarang** [comment]
Hi Brad, the style has been updated in the CSS. You can check this page where the bullets are blue - http://prime.anony.im/products/super/

The content is manageable from the CMS but please make sure the content is added properly.
