### ISSUE TITLE
Error with each content save

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#2]
After changing any content I click "save and publish". The button fades out and the message in the upper right says "publishing ..." for a moment. The content changes are shown on the front-end.

When I then click away from the page in the CMS I get this error implying that there are unsaved changes.

![image](https://cloud.githubusercontent.com/assets/4900157/9436980/d14b6d4e-4a96-11e5-9ff5-1c7e82a5ef36.png)

**Comment by atulnarang** [comment]
This is a Chrome specific issue, please check this thread : https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/65200-Angular-JS-error-in-backoffice-when-using-Chrome
