### ISSUE TITLE
Drop down menu isn't on all main nav options

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#22]
Current the drop down menu is only on 'Personal' and doesn't include all of the items in the hierarchy.

**Comment by atulnarang** [comment]
Brad, this all can be managed via Umbraco Admin, i just enabled it on Personal, either send me what links you want under main navigation or you can select those from Admin

**Comment by bradcbennett** [comment]
Hi Atul,

Can you make all of the 2nd and 3rd tier pages available?

**Comment by atulnarang** [comment]
sure, we have enabled those.
