### ISSUE TITLE
Remove 2 Regional Managers from map

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#24]
Please remove Michael and Noel.

We will also add two Regional Managers. I will send through the new details soon.

**Comment by atulnarang** [comment]
I do not see the remove option in MapManager, does MapManager has any admin account? you can access mapmanager here:
http://mapmanager.anony.im/

We could remove directly from database, but then it might impact some related data in other database tables.

**Comment by bradcbennett** [comment]
Hi Atul,

Please remove it directly from the database. 
Fingers crossed, nothing breaks ... please keep a back-up ;)

**Comment by atulnarang** [comment]
Removed from database
