### ISSUE TITLE
Set up Azure server

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#25]
Hi Atul,

Finally got the client's Azure account set up. Now I need your help setting up the servers.
u: marketing@primesuper.com.au
p: Straightforward1

Of course we'll need a web server and database. How big do you recommend for the web server?
We'll also need a nameserver as their current DNS will be closed with their current host.

Finally, are you able to invite other people to be admins of the account? If so, please invite bradcbennett@gmail.com

Thanks.

**Comment by atulnarang** [comment]
Please advise the server configuration? you check various configurations and pricing here:
http://azure.microsoft.com/en-us/pricing/details/virtual-machines/

current server we have is Basic Tier A2 Instance, let me know if to keep the same setup?

**Comment by bradcbennett** [comment]
Yes, that sounds like a good way to go. Here's what I proposed to the client. In addition, can you let me know the cost for the DNS and email send server?

![image](https://cloud.githubusercontent.com/assets/4900157/10009194/788203b6-611c-11e5-96a3-d2fb17b9396d.png)

**Comment by atulnarang** [comment]
Hi mate, this is the service we need to look at for sending out emails - https://sendgrid.com/pricing

it plugs in well with Microsoft Azure. For the DNS, can you please provide me the domain control panel so that I can login and have a look?

**Comment by bradcbennett** [comment]
For Sendgrid, I'll talk to the client today to get an account set up.

For the DNS, here is their registrar. We'll need to point these guys to our new nameserver. We need to make that request ASAP as it seems to be a manual process. 
https://www.domainregistration.com.au/domains/manage/
The domain password for primesuper.com.au is: DNR194-788-153

**Comment by bradcbennett** [comment]
Sendgrid

Username PrimeSuper
Password PrimeSuper1

**Comment by atulnarang** [comment]
For Sql Server i would recommend we install Sql Server Express edition on the same virtual machine itself, it is free for commercial usage and has limit of 10GB per database.

Let me know
Thanks

**Comment by bradcbennett** [comment]
I'll take your recommendations on the server set up.
Thanks.

**Comment by atulnarang** [comment]
I am setting up a server instance in Australia East, looks like you have not configured any card for billing, so setup will be in Trial mode for now.

**Comment by atulnarang** [comment]
I logged into the Domain panel and seems like we can update it ourselves. See attached screenshot.
![dns](https://cloud.githubusercontent.com/assets/4434840/10041035/83cc66b8-6224-11e5-85bf-491a582d1a72.png)

**Comment by bradcbennett** [comment]
As discussed, I don't think that form automatically changes the records. To get this done I think we need to actually call them and schedule it in. 
Thanks.

**Comment by atulnarang** [comment]
This is the IP which needs to be added 40.126.240.30 for your record.

I will call them tomorrow.

**Comment by atulnarang** [comment]
Brad, i have setup website to use SendGrid as SMTP server, can you please check if emails are working.

**Comment by bradcbennett** [comment]
Great. 
Yeah, the client received the test emails from the Find My Super form.
Thanks.
