### ISSUE TITLE
MapManager Error

### ISSUE THREAD

**Issue by atulnarang** [bradcbennett/PrimeSuper.com.au#27]
with local database we are getting the attached error , also share one username/password for map manager.

![map_manager_error](https://cloud.githubusercontent.com/assets/4434840/9953248/96a498cc-5dfc-11e5-817e-ab457ba99773.PNG)

**Comment by bradcbennett** [comment]
Can this be closed? I don't see this error on prime.anony.im

**Comment by atulnarang** [comment]
Yes
