### ISSUE TITLE
Forms & Publications header 

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#28]
Content is visible behind fixed header. Tested with Chrome on Mac

![image](https://cloud.githubusercontent.com/assets/4900157/9988783/d20a0d10-6096-11e5-8d49-678ef0dbaa68.png)

**Comment by bradcbennett** [comment]
Also, the new icons overlap the text per the image below.

![image](https://cloud.githubusercontent.com/assets/4900157/9988802/fd43257a-6096-11e5-9b42-8d2054b156c3.png)

**Comment by atulnarang** [comment]
check now for new icons.
