### ISSUE TITLE
Unable to edit content in CMS

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#3]
When I go to edit content in the CMS the Main Content area never loads. It just hangs on the "loading ..." message per the screen shot below.

![image](https://cloud.githubusercontent.com/assets/4900157/9508376/2525027e-4c98-11e5-81a5-20492fae0fb7.png)

**Comment by atulnarang** [comment]
Hi Brad, can you please provide the browser name and version?

**Comment by bradcbennett** [comment]
I was using Chrome / Mac.
Although now this WYSIWYG is loading properly...
