### ISSUE TITLE
Main nav vs right nav

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#30]
The spacing and styling for both navigations should be the same. See image below.
Testing in Chrome / Mac, the main nav uses a smaller font and the right nav has less padding.

![image](https://cloud.githubusercontent.com/assets/4900157/9988946/ff6d252a-6097-11e5-81f2-6982cb2c2d8d.png)

**Comment by atulnarang** [comment]
Done, please check

**Comment by bradcbennett** [comment]
The text seems to be slightly to high on the vertical.
Screen shot has designs on left and site on right (Chrome / Mac). 

These are minor things, but lots of little misalignments make the site look messy.

![image](https://cloud.githubusercontent.com/assets/4900157/10009250/369468d0-611d-11e5-8b48-c5676cb009b4.png)

**Comment by atulnarang** [comment]
did a pixel adjustment, please check
