### ISSUE TITLE
Search box text vertical alignment

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#31]
The text in the search box should be the same baseline as the main nav.
Tested Chrome / Mac

![image](https://cloud.githubusercontent.com/assets/4900157/9988988/69c197a8-6098-11e5-9488-cc6dbacf616e.png)

**Comment by atulnarang** [comment]
Done.

**Comment by bradcbennett** [comment]
Looks like the nav and search box text are aligned. But now the search box text isn't vertically centred in the search box.

![image](https://cloud.githubusercontent.com/assets/4900157/9991074/22f3a1e2-60aa-11e5-8f1d-60e4fabfdce4.png)

**Comment by atulnarang** [comment]
If we make that text centered then the whole box won't be centered with the Nav. Please let me know what needs to be centered. Hope this makes sense.

**Comment by bradcbennett** [comment]
Please use the designs as a guide. 
Screenshot below has the site on the left and designs on the right.

![image](https://cloud.githubusercontent.com/assets/4900157/10009232/eaa9ce24-611c-11e5-9d68-374843163a31.png)

**Comment by bradcbennett** [comment]
Alignment looks great.

Now on the search results page there is an errant "search" word appearing over the icon.
Screenshot with Chrome / Mac

![image](https://cloud.githubusercontent.com/assets/4900157/10125973/344a8c24-65ca-11e5-9afa-75af4c4bf926.png)

**Comment by atulnarang** [comment]
fixed
