### ISSUE TITLE
Breadcrumb divider

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#32]
The breadcrumb divider - "|" - is not vertically aligned properly and is missing between the second and third levels. Screen shot of issues below.
Tested Chrome / Mac

![image](https://cloud.githubusercontent.com/assets/4900157/9989055/d5c5bede-6098-11e5-9ae9-28af8913f68b.png)

**Comment by atulnarang** [comment]
Please check now

**Comment by bradcbennett** [comment]
Can we get the pipe - "|" moved up a bit per the designs?

**Comment by atulnarang** [comment]
Moved up little bit more.
