### ISSUE TITLE
Table padding

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#33]
The table padding needs to be tweaked. Left side of image is site (Chrome / Mac), right is design.

![image](https://cloud.githubusercontent.com/assets/4900157/9989105/3161878c-6099-11e5-92a4-433fe609bd21.png)

**Comment by atulnarang** [comment]
please mention which page is this?

**Comment by bradcbennett** [comment]
Was checking the designs against: http://prime.anony.im/employers-self-employed/getting-started/

**Comment by atulnarang** [comment]
increased padding as per design.
