### ISSUE TITLE
Paragraph line height is slightly off

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#34]
Left side is dev site (Chrome / Mac) and right side is designs

![image](https://cloud.githubusercontent.com/assets/4900157/9989129/5959f8dc-6099-11e5-9c57-713fbfb23876.png)

**Comment by atulnarang** [comment]
changed the line height to 23px

**Comment by bradcbennett** [comment]
Hi Atul,

Can you please check the PSDs. It looks to be closer to 24px (Chrome / Mac)
Thanks.


![image](https://cloud.githubusercontent.com/assets/4900157/9991032/d0438976-60a9-11e5-8775-214a0c1a0051.png)

**Comment by atulnarang** [comment]
Done, its 24px now.
