### ISSUE TITLE
Nav and breadcrumb text

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#35]
Can we slightly punch up the nav and breadcrumb text? Its getting slightly lost compared to the designs.
Left side site (Chrome / Mac), right side designs

![image](https://cloud.githubusercontent.com/assets/4900157/9989166/9a3e4c4a-6099-11e5-8777-0f1327c2d1ee.png)

**Comment by atulnarang** [comment]
The nav font has been increased. Breadcrumb has a rollover state and goes bright white on rollover and this has been pre-existing. Please be advised that the fonts in the Photoshop and HTML won't look same because Photoshop has options such as "smooth", "strong" etc.
