### ISSUE TITLE
Search engine

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#37]
Hi Atul,

Can you confirm what we're using for search on the site? Is it Umbraco out of the box or Lucene?

Thanks.

**Comment by atulnarang** [comment]
We have tried to look into the Admin backend and in the html but couldn't find any reference but in the DLLs we can see Lucene dll so I am guessing it's Lucene. To be sure we need to look into the codebase which is not available.

**Comment by bradcbennett** [comment]
Great. Thanks.
