### ISSUE TITLE
Homepage tile is resizing

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#38]
We've tried to upload a new image to the homepage to replace the video tile placeholder. When the image is uploaded at 629x368 it is resized to 500px wide. 

Sample image already uploaded and available here: 
https://www.dropbox.com/home/Prime%20Super%20Rebrand/1.%20Website/Round%208

**Comment by atulnarang** [comment]
The editor auto resizes the image, you will have to explicitly remove width and height from editor, i am looking at a way to disable autoresizing.

**Comment by atulnarang** [comment]
disabled auto-resizing from admin, adjusted the image on home page as well.

**Comment by bradcbennett** [comment]
thanks.
