### ISSUE TITLE
Change Join link in header

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#39]
Mobile and Desktop should link to: https://member.aas.com.au/mjol/join

**Comment by atulnarang** [comment]
https://member.aas.com.au/mjol/join link is not working..should i change it anyway?

**Comment by bradcbennett** [comment]
Yes please 

btw, I see this at that link
![image](https://cloud.githubusercontent.com/assets/4900157/10038092/f0234b5a-6202-11e5-90ed-6d9efcb37435.png)

**Comment by atulnarang** [comment]
FYI, i am getting this at link:

![link](https://cloud.githubusercontent.com/assets/4434840/10039458/d34900e6-61ef-11e5-9cf0-27103b614692.PNG)

**Comment by atulnarang** [comment]
done

**Comment by bradcbennett** [comment]
Still the old link for me.
Please advise

![image](https://cloud.githubusercontent.com/assets/4900157/10062275/3ae8f882-62a4-11e5-94c5-3c555cf743b8.png)

**Comment by atulnarang** [comment]
my bad, corrected now

**Comment by bradcbennett** [comment]
The client gave us the wrong link. Please use this link for the desktop and mobile versions:
https://member.aas.com.au/mjol/join/pr 

(this has a "pr" at the end)

**Comment by atulnarang** [comment]
corrected
