### ISSUE TITLE
Unable to delete 'Economic & market summary'

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#4]
We would like to remove the entire set of pages under Tools & Resources > News Centre > Economic & market summary. However, when I try to delete that folder I get the error below. 
If I hit 'close' on this error, I get the delete confirmation screen. If I hit 'ok' on the confirmation screen, I get the error again.

![image](https://cloud.githubusercontent.com/assets/4900157/9508454/df9ab590-4c98-11e5-8c24-643cee9a95f2.png)

**Comment by atulnarang** [comment]
Please try now
