### ISSUE TITLE
Find My Super mobile formatting

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#47]
Hi Atul,

Three tweaks on the Find My Super mobile form.
1) Please have the titles sit above the fields. Currently they sit at the bottom of the field above
2) left align State / Territory field
3) Fix styling around "tick box to consent"

![image](https://cloud.githubusercontent.com/assets/4900157/10154787/230e7584-66af-11e5-89f6-a6147a792827.png)

**Comment by atulnarang** [comment]
fixed

**Comment by bradcbennett** [comment]
Looks great!

From:  Atul Narang <notifications@github.com>
Reply-To:  "bradcbennett/PrimeSuper.com.au"
<reply+004ac53dc64e05ae61101a98ec9f52af66b62c84a8313a4f92cf00000001122208379
2a169ce067bfbf2@reply.github.com>
Date:  Tuesday, 29 September 2015 6:05 pm
To:  "bradcbennett/PrimeSuper.com.au" <PrimeSuper.com.au@noreply.github.com>
Cc:  Brad Bennett <brad@thehallway.com.au>
Subject:  Re: [PrimeSuper.com.au] Find My Super mobile formatting (#47)


fixed


Reply to this email directly or view it on GitHub
<https://github.com/bradcbennett/PrimeSuper.com.au/issues/47#issuecomment-14
3978776> .
