### ISSUE TITLE
Homepage Latest News Feed

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#6]
Here is the updated feed for the homepage. Looks like the "Latest News" header is no longer in the feed, so we'll need that in our part of the page.
http://meltwaternews.com/ext/a3logics/APAC/SNS-74700/Index.html

**Comment by atulnarang** [comment]
This has been completed @bradcbennett

**Comment by bradcbennett** [comment]
Thanks.
Are we able have the height of the iframe dynamically stretch all the way to the orange footer?
Looks a bit odd with the white space below the news feed. 

![image](https://cloud.githubusercontent.com/assets/4900157/9836004/2ba4773c-5a4a-11e5-9e6b-deb0bf3222d5.png)

**Comment by atulnarang** [comment]
This has been done so please review and let me know.
