### ISSUE TITLE
Landing page header spacing

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#7]
The spacing around the h2.landingtitle doesn't match the designs.
Also, should this be an h1 instead of h2?

Please see http://prime.anony.im/personal/ . 
Tested in Firefox and Chrome on mac.

![image](https://cloud.githubusercontent.com/assets/4900157/9723526/869db204-5606-11e5-8b94-aacaf846b72c.png)

**Comment by atulnarang** [comment]
Done, please review.
