### ISSUE TITLE
Text on landing page header image doesn't match designs

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#8]
Please see designs.
- stretches too far to the left
- does not have blue box in background
- letter spacing looks a bit off

Please see "We provide personal support to members and employers" here: http://prime.anony.im/about-us/ 

Tested Firefox and Chrome on Mac

![image](https://cloud.githubusercontent.com/assets/4900157/9723580/858bcbd4-5607-11e5-8833-3f18993feb8b.png)

**Comment by atulnarang** [comment]
We have not yet got the PSD of About Us page, we are working through the PSD's as they are made available in dropbox.
Blue area in banner is part of the image and can be uploaded from the CMS

**Comment by bradcbennett** [comment]
Atul,

There won't be a specific design for the About Us page. This uses the landing page template (same as Personal landing page). Please review those designs for correct text placement.

**Comment by atulnarang** [comment]
Thanks Brad. Unfortunately I haven't seen a PSD for the Personal landing page. Previously we had the following PSDs -

1. Homepage
2. Useful Links 
3. Forms & Publications 
4. Our Operations 
5. Latest News
6. Low fees and charges 
7. Investment Performance
8. Getting Started

and now in the current dropbox folder I can see 4 other pages. Can you please provide the PSD for the personal page?

**Comment by bradcbennett** [comment]
Hi Atul,

The Personal landing page has been up on Dropbox for a couple weeks: https://www.dropbox.com/home/Prime%20Super%20Rebrand/1.%20Website/Final%20PSDs/24%2008%202015/Desktop?select=PrimeSuper_Personal_V2.psd 

This is where the various file deliveries live: https://www.dropbox.com/home/Prime%20Super%20Rebrand/1.%20Website/Final%20PSDs 

Will call this morning to discuss.

**Comment by atulnarang** [comment]
The solution for this is to upload the banner with the blue box and title which will rule out any issue related to the title length as well.

**Comment by bradcbennett** [comment]
Atul,
I'm not sure that's the best solution. Putting the text in the image makes it more difficult to content manage and worse for SEO. 
Why haven't you gone with the solution we discussed on the phone? 
We could potentially make the blue boxes as part of the header images, but you'll still need to place the header text in the correct place.
See screen shot with site on left and designs on right (Chrome / Mac)

Please let me know which solution is best. 

![image](https://cloud.githubusercontent.com/assets/4900157/10009306/fc41da0e-611d-11e5-85d4-7b7e8a11dd2f.png)

**Comment by atulnarang** [comment]
fixed
