### ISSUE TITLE
<strong> text doesn't appear properly bolded

### ISSUE THREAD

**Issue by bradcbennett** [bradcbennett/PrimeSuper.com.au#9]
In the last paragraph on this page the words "surprisingly straightforward" are bolded: http://prime.anony.im/about-us/who-we-are/ 
This doesn't appear in Firefox or Chrome on Mac.

Please use Avenir Black for bolded text.

**Comment by atulnarang** [comment]
We followed the photoshop design and fonts being used are Avenir Medium and Avenir Heavy in the PSD files, if you have any guidelines for diff elements please share it.

**Comment by bradcbennett** [comment]
Do you have Avenir Black to work with?

**Comment by atulnarang** [comment]
Yes we have Avenir lt Std Black, i have set that default for h3 and strong elements.
